export const NEW_PROPERTY_REQUEST = "NEW_PROPERTY_REQUEST";
export const NEW_PROPERTY_SUCCESS = "NEW_PROPERTY_SUCCESS";
export const NEW_PROPERTY_RESET = "NEW_PROPERTY_RESET";
export const NEW_PROPERTY_FAIL = "NEW_PROPERTY_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
